services:
  bbpy:
    image: bot-bollinger-bybit
    container_name: bbpy
    restart: always
    # stdin_open: true
    env_file:
      - ./.prod.env
    volumes:
      - ./:/app/logs
      - ./:/app
