services:
  bbpy:
    image: fgiardina/bbpy:latest
    container_name: bbpy
    restart: always
    # stdin_open: true
    env_file:
      - ./.prod.env
    volumes:
      - ./:/app/logs
      - ./scripts:/app
